### ISSUE TITLE
only initialization or only run workload flags

### ISSUE THREAD

**Issue by sagyvolkov** [cloud-bulldozer/ripsaw#182] opened 2019-08-13 23:57 UTC
for database workloads, like pgbench, sysbench or YCSB, it will be a good idea to allow a cr to only run the initialization part or just the actual workload.
The reason is that loading of the database can take long time, especially on large databases or on many small databases, and you don't want to go through this process on every run.

**Comment by aakarshg** [comment] 2019-11-04 20:34
closing this as it's a duplicate of #169

**Closed by aakarshg** 2019-11-04 20:34 UTC

**Comment by aakarshg** [comment] 2019-11-11 18:56
@sagyvolkov just letting you know that I've opened #247 to address this issue. Please let me know if this would suffice or would you like any additional changes/ or open to suggestions.
